services:
  deck-discord-bot:
    build: .
    container_name: deck-discord-bot
    environment:
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_USERNAME}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - BOARD_ID=${BOARD_ID}
      - DISCORD_THREAD_ID=${DISCORD_THREAD_ID}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-60}
      - TZ=America/Edmonton
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
